-- Schema for CLASSIC_SOCKS
PRAGMA foreign_keys = ON;

-- CATEGORIES
CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- PRODUCTS
CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category_id INT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- PRICE_LIST
CREATE TABLE IF NOT EXISTS price_list (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  product_id INT NOT NULL,
  buy_price DECIMAL(12,4) DEFAULT 0,
  general_price DECIMAL(12,4) DEFAULT 0,
  special_price DECIMAL(12,4) DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- CLIENTS
CREATE TABLE IF NOT EXISTS clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  alias VARCHAR(255),
  adress TEXT,
  lat DECIMAL(10,7) NULL,
  lng DECIMAL(10,7) NULL,
  observations TEXT,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- CLIENT_ROUTES
CREATE TABLE IF NOT EXISTS client_routes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  day VARCHAR(50) NOT NULL,
  visit_order INT DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- SALES
CREATE TABLE IF NOT EXISTS sales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_routes_id INT NOT NULL,
  client VARCHAR(255) NOT NULL,
  quantity DECIMAL(12,4) DEFAULT 0,
  price DECIMAL(12,4) DEFAULT 0,
  observations TEXT,
  date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (client_routes_id) REFERENCES client_routes(id) ON DELETE CASCADE
);

-- ORDERS
CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  price_list_id INT NULL,
  buy_price DECIMAL(12,4) DEFAULT 0,
  quantity INT DEFAULT 0,
  buy_date DATE NULL,
  reception_date DATE NULL,
  everything_is_ok TINYINT(1) DEFAULT 0,
  observations TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (price_list_id) REFERENCES price_list(id) ON DELETE SET NULL
);
